// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using financemanager.Modell;

namespace financemanager.Migrations
{
    [DbContext(typeof(BilanceContext))]
    partial class BilanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("financemanager.Modell.VRTransaction", b =>
                {
                    b.Property<int>("VRTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BICClient")
                        .IsRequired()
                        .HasColumnName("bic client")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("BookingDate")
                        .IsRequired()
                        .HasColumnName("bookin date")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("BookingText")
                        .IsRequired()
                        .HasColumnName("booking text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnName("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientAccount")
                        .HasColumnName("client account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditorID")
                        .IsRequired()
                        .HasColumnName("creditor id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBANClient")
                        .IsRequired()
                        .HasColumnName("iban client")
                        .HasColumnType("nvarchar(22)")
                        .HasMaxLength(22);

                    b.Property<string>("MandateReference")
                        .HasColumnName("mandate reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderAccount")
                        .HasColumnName("order account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeBIC")
                        .IsRequired()
                        .HasColumnName("payee BIC")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("PayeeIBAN")
                        .IsRequired()
                        .HasColumnName("payee IBAN")
                        .HasColumnType("nvarchar(22)")
                        .HasMaxLength(22);

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasColumnName("name payee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeofUse")
                        .IsRequired()
                        .HasColumnName("purpose of use")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaldoAfterBooking")
                        .IsRequired()
                        .HasColumnName("saldo after booking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxRelevant")
                        .HasColumnName("tax relevant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueDate")
                        .IsRequired()
                        .HasColumnName("value date")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("VRTransactionID");

                    b.ToTable("VRTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
